name: 'Build Maven Sync'
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]
permissions:
  contents: 'write'
env:
  GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: 'false'
  ORG_GRADLE_PROJECT_signingInMemoryKey: '${{ secrets.SIGNING_KEY }}'
  ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: '${{ secrets.SIGNING_PASSWORD }}'
  ORG_GRADLE_PROJECT_mavenCentralUsername: '${{ secrets.SONATYPEUSERNAME }}'
  ORG_GRADLE_PROJECT_mavenCentralPassword: '${{ secrets.SONATYPEPASSWORD }}'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    # https://github.com/hmarr/debug-action
    - uses: 'hmarr/debug-action@cd1afbd7852b7ad7b1b7a9a1b03efebd3b0a1820' # v3.0.0

    # https://github.com/zgosalvez/github-actions-ensure-sha-pinned-actions
    - uses: 'zgosalvez/github-actions-ensure-sha-pinned-actions@25ed13d0628a1601b4b44048e63cc4328ed03633' # v3.0.22

    # https://github.com/actions/checkout
    - name: 'checkout'
      uses: 'actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683' # v4.2.2

    # https://github.com/actions/setup-java
    - name: 'Set up JDK'
      uses: 'actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12' # v4.7.0
      with:
        java-version: '21'
        distribution: 'temurin'
        check-latest: 'true'

    # https://github.com/gradle/actions/tree/main/setup-gradle
    - name: 'Set up Gradle'
      uses: "gradle/actions/setup-gradle@94baf225fe0a508e581a564467443d0e2379123b" # v4.3.0

    # https://github.com/gradle/actions/tree/main/dependency-submission
    - name: "Generate and submit dependency graph"
      uses: "gradle/actions/dependency-submission@94baf225fe0a508e581a564467443d0e2379123b" # v4.3.0
      with:
        cache-cleanup: 'never'
        build-scan-publish: false
        dependency-graph-exclude-projects: "^:(build-logic|buildSrc|.*[Tt]test.*)"
        dependency-graph-exclude-configurations: ".*[Tt]est.*Classpath"

    - name: 'Build'
      run: './gradlew build --info --scan --stacktrace'

    - name: 'Publish'
      run: './gradlew publish --info --stacktrace --no-configuration-cache'
